api_key: R720giGypXGlUEQKdDyPYQ7iZm67Ui8Vt1DTXM90LjBE0JmdxB2PjOyg9hkYio1mJWbpNlLcseoJxrbY7dGA
api_secret: bsFHtRA26RVvESacDUudegStZj70A3sS8gaNb9F80jYjtXg6uGTBTBvpc7b6A3nVkLGQqEEwWc3rdUdj70Q
data_csv: data/historical/ETH-USDT/ETH-USDT_005_20251001_20260601.csv
data_end: '2026-06-01'
data_start: '2025-10-01'
dataset_id: ETH-USDT_005
enable_learner: false
hunter_depth: 5
hunter_iterations: 200
hunter_learning_rate: 0.1
hunter_model_path: models/hunter/ETH-USDT/ETH-USDT_006.cbm
max_lag: 10
model_id: ETH-USDT_006
prob_threshold: 0.5
sl_atr_mult: 0.8
spotter_max_lag: 2
spotter_order: 5
spotter_window: 50
symbol: ETH-USDT
target_horizon: 50
testnet: true
tp_atr_mult: 4.0
use_critic: false
